### ISSUE TITLE
Add the license field to info.rkt

### ISSUE THREAD

**Issue by sorawee** [Metaxal/text-table#10]
It would be nice to add the [`license` field](https://docs.racket-lang.org/pkg/metadata.html#%28idx._%28gentag._8._%28lib._pkg%2Fscribblings%2Fpkg..scrbl%29%29%29). However, it's unclear what version of LGPL do you want to use, and whether you want to convert the package to Apache 2 + MIT following Racket's license change. So I create this issue instead.

**Comment by Metaxal** [comment]
Oh yes, you're right, I should change the license to Apache2+MIT indeed. Thanks for the reminder. I'll (try to remember to) do that later this week, hopefully.

**Comment by Metaxal** [comment]
Fixed

**Comment by Metaxal** [comment]
a
