### ISSUE TITLE
Header border

### ISSUE THREAD

**Issue by sorawee** [Metaxal/text-table#12]
I want to create a table with a header. In the documentation, the `(Name Speed ... Unit)` example seems to be exactly what I want. The border is created by specifying `#:row-sep? '(#t #f)`, which expands to `'(#t #f #f .....)` via `pattern-list->list`.

The problem is that when I have exactly one row of data (not counting the header), it fails:

```
> (print-table #:row-sep? '(#t #f) '(("header") ("first row")))
make-list: contract violation
  expected: exact-nonnegative-integer?
  given: -1
  argument position: 1st
```

Instead, `'(#t #f ...)` works.

```
> (print-table #:row-sep? '(#t #f ...) '(("header") ("first row")))
┌─────────┐
│header   │
├─────────┤
│first row│
└─────────┘
```

But then if I don't have any row at all (besides the header), it fails again:

```
> (print-table #:row-sep? '(#t #f ...) '(("header")))
make-list: contract violation
  expected: exact-nonnegative-integer?
  given: -1
  argument position: 1st
```

So a couple of things:

1. Is `(pattern-list->list '(a b) 1)`  _supposed_ to be the same as `(pattern-list->list '(a b ...) 1)`? That is to say, is the error in `(pattern-list->list '(a b) 1)` expected, or a bug?
2. In case that the error in `(pattern-list->list '(a b) 1)` is expected, can we change the example in the documentation somehow so that it doesn't mislead that `#:row-sep? '(#t #f)` is the right thing to use.
3. Any luck to get zero rows (not counting the header) working? (this one is pretty "degenerated", so it's fine if you don't want to consider it)

**Comment by Metaxal** [comment]
Thanks for the detailed report!

There's clearly some inconsistency that needs to be resolved here. At first sight I'd say that `'(#t #f)` should behave like `'(#t #f ...)`.

Regarding zero rows, there should at least be a clearer error message. If it doesn't error, what would you expect the output to be?

**Comment by sorawee** [comment]
Perhaps 

```
┌──────┐
│header│
└──────┘
```

**Comment by Metaxal** [comment]
Let me know if the recent changes work well for you.
