### ISSUE TITLE
print-table should not be a macro

### ISSUE THREAD

**Issue by sorawee** [Metaxal/text-table#13]
I want to `dynamic-require` `print-table`, but that can't be done because it is a macro, even though it doesn't need to be.

**Comment by Metaxal** [comment]
Yes, `print-table` doesn't need to be a macro, but it's really just a small convenience form on top of `table->string`.

I guess I could use `keyword-apply` instead, would that work for you?

In the meantime, you can just require `table->string` and wrap it with `displayln`.

**Comment by sorawee** [comment]
Yep, I think `make-keyword-procedure` + `keyword-apply` would work, and yes, the workaround works. It's what I have been using.
