### ISSUE TITLE
#:->string passes strings thru without running the given function

### ISSUE THREAD

**Issue by czrpb** [Metaxal/text-table#15]
PROBLEM: One of the columns in my data was a very long string.

OBJECTIVE: I wanted to truncate. I attempted to use `#:->string` thusly:

```scheme
(print-table
  #:->string (list ~a (curry ~a #:max-width 3) ~a)
  `(("a" "bbbbb" "c"))
  )
┌─┬─────┬─┐
│a│bbbbb│c│
└─┴─────┴─┘
```

hopefully resulting in:

```scheme
> (print-table
    (map (lambda (row)
           (map (lambda (f x) (f x))
                (list ~a (curry ~a #:max-width 3) ~a)
                row
                )
           )
         `(("a" "bbbbb" "c"))
         )
    )
┌─┬───┬─┐
│a│bbb│c│
└─┴───┴─┘
```

It seems when a cell is a string it is simply returned and not run thru the given function; this might be the code doing this, note the `string?` check:

```scheme
  (define ll1
    (map (λ (row) (map (λ (cell ->string)
                         (define res (string-split (if (string? cell) cell (->string cell))
                                                   "\n"))
                         (if (empty? res) '("") res))
                       row
                       ->string-list))
         ll))

```

can we have it just run the func in `->string` regardless of type?

**Comment by maueroats** [comment]
1. From one point of view, it does not make sense to have a "convert to string" function (this is the meaning of `->string`) that gets called on strings.
2. Why don't you just run your truncation function on the column that is too long before you print it?

**Comment by Metaxal** [comment]
Thanks for the report!

Indeed the docs are not clear about this: `#:->string` is a converter, not a formatter, and does not touch strings. I've updated the docs.

I guess we could add a `#:format [fmt #f]` argument where `fmt` could be a formatting procedure that would take precedence over `->string`, but I think that would make the interface more confusing than helpful. If I get several requests about this I'd reconsider though.

(Note that the behaviour of the `->string` argument cannot be changed, to maintain backward compatibility, as some code such as my own rely on this behaviour.)

**Comment by czrpb** [comment]
Hi! Thx for the replies!

1. I have indeed solved it by `map`ping over the data before giving it to `text-table`.
2. I think because Im not steeped in the conventions, I read `->string` to include the possibility of formatting as you say. So, wrong understanding on my part.
3. Sounds good on waiting for more input from others, which I dont expect to happen as it hasnt yet! :)
